# NEXO core template.
# create-client.js reemplaza automáticamente estos valores en cada cliente.
name = "nexo-core"
compatibility_date = "2026-06-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "nexo-core_db"
database_id = "7c354e18-2fc3-45e5-82ae-c2e106c0a17b"

[[d1_databases]]
binding = "DB_AUDIT"
database_name = "nexo-core_audit_db"
database_id = "31fdde5f-bb10-4b60-9db1-49d506811200"
